[package]
name = "omni-kern"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
half.workspace = true
kern-manifest.workspace = true
kern-runtime.workspace = true
memmap2.workspace = true
safetensors.workspace = true
serde_json.workspace = true

[lints]
workspace = true
