[package]
name = "omni-qwen3-tts"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
omni-cuda.workspace = true
omni-engine.workspace = true

anyhow.workspace = true
bytes.workspace = true
half.workspace = true
memmap2.workspace = true
rand.workspace = true
safetensors.workspace = true
serde.workspace = true
serde_json.workspace = true
tokenizers.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
