//! The contract between the front end and an image engine.
//!
//! The same shape as the speech contract: the front end holds a [`Handle`],
//! the engine drains the matching [`Inbox`], and cancellation is the dropped
//! event receiver. A [`Generation`] only exists after [`ImageInfo::check`]
//! accepted it.
//!
//! Pictures cross the boundary as 8-bit RGB, row-major, with no row padding.
//! PNG and base64 are the front end's business; the engine never encodes.

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::fmt;
use std::sync::Arc;
use std::sync::atomic::AtomicU64;
use std::sync::atomic::Ordering;
use std::sync::mpsc;

use bytes::Bytes;
use serde_json::Value;
use tokio::sync::mpsc::UnboundedReceiver;
use tokio::sync::mpsc::UnboundedSender;
use tokio::sync::mpsc::unbounded_channel;

use crate::Extra;
use crate::Finish;
use crate::Invalid;
use crate::Load;
use crate::Rejected;

/// Output dimensions in pixels.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Size {
    pub width: u32,
    pub height: u32,
}

impl fmt::Display for Size {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}x{}", self.width, self.height)
    }
}

impl std::str::FromStr for Size {
    type Err = String;

    /// `WIDTHxHEIGHT`, as OpenAI's `size` spells it.
    fn from_str(s: &str) -> Result<Self, String> {
        let parse = |x: &str| x.parse::<u32>().ok().filter(|&v| v > 0);
        match s.split_once('x').and_then(|(w, h)| parse(w).zip(parse(h))) {
            Some((width, height)) => Ok(Self { width, height }),
            None => Err(format!("expected WIDTHxHEIGHT, got `{s}`")),
        }
    }
}

/// What an image engine serves, fixed at launch.
#[derive(Clone, Debug)]
pub struct ImageInfo {
    pub model: String,
    /// The only sizes the model generates; `size` must name one.
    pub sizes: BTreeSet<Size>,
    /// What an omitted or `auto` size means.
    pub default_size: Size,
    pub max_n: u32,
    pub max_prompt_chars: usize,
    /// Keys the engine accepts inside a request's `extra` object, and their values.
    pub extra: BTreeMap<String, Extra>,
}

/// The unchecked fields of an image request, as the protocol layer parsed them.
#[derive(Clone, Debug, Default)]
pub struct Draft {
    pub prompt: String,
    /// `None` for an omitted or `auto` size.
    pub size: Option<Size>,
    pub n: Option<u32>,
    pub extra: BTreeMap<String, Value>,
}

/// A request the engine can run as is.
#[derive(Clone, Debug)]
pub struct Generation {
    pub id: u64,
    pub prompt: String,
    pub size: Size,
    pub n: u32,
    pub extra: BTreeMap<String, Value>,
}

impl ImageInfo {
    /// Accepts a draft this engine can serve, or names the first field it cannot.
    pub fn check(&self, draft: Draft) -> Result<Generation, Invalid> {
        let invalid = |param, message: String| Err(Invalid { param, message });
        let chars = draft.prompt.chars().count();
        if draft.prompt.trim().is_empty() {
            return invalid("prompt", "must not be empty".into());
        }
        if chars > self.max_prompt_chars {
            return invalid("prompt", format!("{chars} characters, the limit is {}", self.max_prompt_chars));
        }
        let size = draft.size.unwrap_or(self.default_size);
        if !self.sizes.contains(&size) {
            let sizes: Vec<String> = self.sizes.iter().map(Size::to_string).collect();
            return invalid(
                "size",
                format!("{size} is not generated by `{}`; use one of {}", self.model, sizes.join(", ")),
            );
        }
        let n = draft.n.unwrap_or(1);
        if !(1..=self.max_n).contains(&n) {
            return invalid("n", format!("{n} is outside 1..={}", self.max_n));
        }
        for (key, value) in &draft.extra {
            match self.extra.get(key) {
                None => return invalid("extra", format!("`{key}` is not an extension of model `{}`", self.model)),
                Some(spec) => {
                    spec.check(value).map_err(|m| Invalid { param: "extra", message: format!("`{key}`: {m}") })?
                }
            }
        }
        Ok(Generation { id: 0, prompt: draft.prompt, size, n, extra: draft.extra })
    }
}

/// One finished picture: `size.width * size.height * 3` bytes of RGB.
#[derive(Clone, Debug)]
pub struct Rgb {
    pub size: Size,
    pub pixels: Bytes,
}

/// One step of a request's output stream: its `n` pictures, then exactly one `Done`.
#[derive(Clone, Debug)]
pub enum Event {
    Image(Rgb),
    Done(Finish),
}

pub struct Submission {
    pub generation: Generation,
    pub sink: UnboundedSender<Event>,
}

/// The front end's side of the channel.
#[derive(Clone)]
pub struct Handle {
    pub info: Arc<ImageInfo>,
    pub load: Arc<Load>,
    tx: mpsc::SyncSender<Submission>,
    next_id: Arc<AtomicU64>,
}

/// The engine's side of the channel.
pub struct Inbox {
    pub info: Arc<ImageInfo>,
    pub load: Arc<Load>,
    pub rx: mpsc::Receiver<Submission>,
}

/// A connected handle and inbox; `queue` bounds submissions not yet taken by the engine.
pub fn channel(info: ImageInfo, queue: usize) -> (Handle, Inbox) {
    let info = Arc::new(info);
    let load = Arc::new(Load::default());
    let (tx, rx) = mpsc::sync_channel(queue);
    let handle = Handle { info: info.clone(), load: load.clone(), tx, next_id: Arc::new(AtomicU64::new(1)) };
    (handle, Inbox { info, load, rx })
}

impl Handle {
    /// Queues a request without blocking; the receiver yields its pictures then exactly one `Done`.
    pub fn submit(&self, mut generation: Generation) -> Result<UnboundedReceiver<Event>, Rejected> {
        generation.id = self.next_id.fetch_add(1, Ordering::Relaxed);
        let (sink, events) = unbounded_channel();
        match self.tx.try_send(Submission { generation, sink }) {
            Ok(()) => Ok(events),
            Err(mpsc::TrySendError::Full(_)) => Err(Rejected::Full),
            Err(mpsc::TrySendError::Disconnected(_)) => Err(Rejected::Stopped),
        }
    }
}
